using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using ReadGlyph.Models;

namespace ReadGlyph.Services;

/// <summary>
/// C 源码生成器 — 将取模后的像素数据输出为嵌入式 C 数组文件
/// </summary>
public class CCodeGenerator
{
    private readonly FontEngine _fontEngine = new();
    private readonly ImageEngine _imageEngine = new();

    // ═════════════ 字体 .c ═════════════

    /// <summary>生成字体 .c 文件到 outputPath</summary>
    /// <param name="outputPath">完整输出路径，如 "D:/lvgl/src/font_16px.c"</param>
    /// <param name="source">字体源（需解析 fonts/ 相对路径）</param>
    /// <param name="asset">字体资产（含 Glyphs 字符集）</param>
    /// <param name="dataDir">App.DataDir，用于拼接源文件绝对路径</param>
    public void GenerateFont(string outputPath, FontSource source, FontAsset asset, string dataDir)
    {
        var fontPath = Path.Combine(dataDir, source.FilePath);
        var codepoints = ParseCodepoints(asset.Glyphs);
        var glyphs = _fontEngine.Rasterize(fontPath, asset.Size, asset.Bpp, codepoints);

        var dir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(dir))
            Directory.CreateDirectory(dir);

        var sb = new StringBuilder();
        var name = Path.GetFileNameWithoutExtension(asset.Name);

        // ── 按 Unicode 排序 glyphs（确保 glyph_id 和 bitmap_index 对应）──
        var sortedGlyphs = glyphs.OrderBy(g => g.Codepoint).ToList();

        // ── 位图数据构建（placeholder 占 index 0，glyph 从 1 开始）──
        // 为 placeholder 预留 index 0 的空位（添加一个 0-byte bitmap）
        int bmpIdx = 0;
        var bmpList = new List<byte[]>();
        var dscList = new List<(uint cp, int ofs, int adv, int w, int h, int ox, int oy)>();
        var uniqueBitmaps = new Dictionary<string, int>();

        // placeholder 不占实际 bitmap 空间，但保留 index 0
        // 第一个有效 glyph 从 index 0 开始（placeholder 不读取 bitmap）

        foreach (var g in sortedGlyphs)
        {
            var bmp = g.PackedBitmap;
            int ofs;

            if (bmp.Length == 0)
            {
                ofs = 0;  // 空位图统一使用 index 0（与 placeholder 共用）
            }
            else
            {
                var key = Convert.ToBase64String(bmp);
                if (uniqueBitmaps.TryGetValue(key, out var cachedOfs))
                {
                    ofs = cachedOfs;
                }
                else
                {
                    ofs = bmpIdx;
                    uniqueBitmaps[key] = ofs;
                    bmpList.Add(bmp);
                    bmpIdx += bmp.Length;
                }
            }

            dscList.Add((g.Codepoint, ofs, g.AdvanceX, g.Width, g.Height, g.OffsetX, g.OffsetY));
        }

        sb.AppendLine("/* Generated by ReadGlyph — DO NOT EDIT */");
        sb.AppendLine($"/* Font: {source.DisplayName}, Size: {asset.Size}px, Bpp: {asset.Bpp}, {glyphs.Count} glyphs */");
        sb.AppendLine();
        WriteFontLvgl9(sb, name, asset, sortedGlyphs, bmpList, bmpIdx, dscList);

        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }

    // ═════════════ 图片 .c ═════════════

    /// <summary>生成图片 .c 文件到 outputPath</summary>
    public void GenerateImage(string outputPath, ImageSource source, ImageAsset asset, string dataDir)
    {
        var imgPath = Path.Combine(dataDir, source.FilePath);
        var result = _imageEngine.Process(imgPath, asset.Width, asset.Height, asset.Format);

        var dir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(dir))
            Directory.CreateDirectory(dir);

        var sb = new StringBuilder();
        var name = Path.GetFileNameWithoutExtension(asset.Name);

        sb.AppendLine("/* Generated by ReadGlyph — DO NOT EDIT */");
        sb.AppendLine($"/* Image: {source.DisplayName}, {result.Width}x{result.Height}, {asset.Format} */");
        sb.AppendLine();
        WriteImageLvgl9(sb, name, asset, result);

        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }

    // ═════════════ 工具 ═════════════

    /// <summary>将 Glyphs 字符串解析为 Unicode 码点列表（处理代理对）</summary>
    private static List<uint> ParseCodepoints(string glyphs)
    {
        var list = new List<uint>(glyphs.Length);
        foreach (var rune in glyphs.EnumerateRunes())
            list.Add((uint)rune.Value);
        return list;
    }

    // ═════════════ 格式写入器 ═════════════

    private static void WriteFontLvgl9(StringBuilder sb, string name, FontAsset asset,
        List<FontEngine.GlyphData> glyphs, List<byte[]> bmpList, int bmpIdx,
        List<(uint cp, int ofs, int adv, int w, int h, int ox, int oy)> sorted)
    {
        // 确保变量名是合法 C 标识符（不能以数字开头）
        var safeName = !char.IsLetter(name[0]) && name[0] != '_' ? "font_" + name : name;

        // ── 度量计算（提前，用于 ofs_y 转换）──
        int baseLine = glyphs.Count > 0 ? glyphs.Max(g => g.OffsetY) : asset.Size;
        int lineHeight = glyphs.Count > 0 ? glyphs.Max(g => g.OffsetY + g.Height) : asset.Size * 4 / 3;
        if (lineHeight < baseLine + 2) lineHeight = baseLine + 2;
        int underlinePos = -(asset.Size / 16 + 1);
        int underlineThick = Math.Max(1, asset.Size / 16);

        // ── stride 说明 ──
        // ReadGlyph 使用紧密打包（每行数据紧接上一行），兼容 LVGL stride=0
        // stride=0 表示不对齐，LVGL 会按像素顺序读取 bitmap

        sb.AppendLine("#include \"lvgl.h\"");
        sb.AppendLine();
        sb.AppendLine("#ifndef LV_ATTRIBUTE_LARGE_CONST");
        sb.AppendLine("#define LV_ATTRIBUTE_LARGE_CONST const");
        sb.AppendLine("#endif");
        sb.AppendLine();

        // 位图
        sb.AppendLine($"/* bitmap data — {asset.Bpp}bpp, {bmpIdx} bytes total */");
        sb.AppendLine($"static LV_ATTRIBUTE_LARGE_CONST const uint8_t __{safeName}_bitmap[{bmpIdx}] = {{");
        int col = 0;
        foreach (var bmp in bmpList)
        {
            foreach (var b in bmp)
            {
                sb.Append($"0x{b:X2}, ");
                if (++col % 16 == 0) sb.AppendLine();
            }
        }
        if (col % 16 != 0) sb.AppendLine();
        sb.AppendLine("};");
        sb.AppendLine();

        // 描述符（index 0 为占位符，glyph_id 从 1 开始）
        // LVGL ofs_y = baseline - FreeType offsetY（从行顶部到字形顶部的距离）
        sb.AppendLine("/* glyph descriptors */");
        sb.AppendLine($"static const lv_font_fmt_txt_glyph_dsc_t __{safeName}_dsc[{sorted.Count + 1}] = {{");
        sb.AppendLine("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}, /* placeholder */");
        foreach (var (cp, ofs, adv, w, h, ox, oy) in sorted)
        {
            // 转换 ofs_y：LVGL 使用行顶部坐标系，FreeType 使用基线坐标系
            int lvglOfsY = baseLine - oy;
            // 转换 adv_w：LVGL 使用 8.4 定点格式（实际像素值 × 16）
            int lvglAdvW = adv * 16;
            // 获取实际字符（支持 Unicode）
            string charStr = char.ConvertFromUtf32((int)cp);
            string label = $" /* U+{cp:X04} '{charStr}' */";
            if (w == 0 || h == 0)
                sb.AppendLine($"    {{.bitmap_index = 0, .adv_w = {lvglAdvW}, .box_w = {w}, .box_h = {h}, .ofs_x = {ox}, .ofs_y = 0}}, {label}");
            else
                sb.AppendLine($"    {{.bitmap_index = {ofs}, .adv_w = {lvglAdvW}, .box_w = {w}, .box_h = {h}, .ofs_x = {ox}, .ofs_y = {lvglOfsY}}}, {label}");
        }
        sb.AppendLine("};");
        sb.AppendLine();

        // cmap
        var ranges = new List<(uint rangeStart, ushort rangeLen, ushort glyphIdStart)>();
        int idx = 0;
        while (idx < sorted.Count)
        {
            uint rangeStart = sorted[idx].cp;
            ushort glyphIdStart = (ushort)(idx + 1);  // glyph_id 从 1 开始，0 是占位符
            ushort rangeLen = 1;
            idx++;
            while (idx < sorted.Count && sorted[idx].cp == rangeStart + rangeLen)
            {
                rangeLen++;
                idx++;
            }
            ranges.Add((rangeStart, rangeLen, glyphIdStart));
        }

        sb.AppendLine("/* character map */");
        sb.AppendLine($"static const lv_font_fmt_txt_cmap_t __{safeName}_cmaps[{ranges.Count}] = {{");
        foreach (var (start, len, gidStart) in ranges)
            sb.AppendLine($"    {{.range_start = 0x{start:X04}, .range_length = {len}, .glyph_id_start = {gidStart}, .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY}},");
        sb.AppendLine("};");
        sb.AppendLine();

        sb.AppendLine("/* font format descriptor */");
        sb.AppendLine($"const lv_font_fmt_txt_dsc_t {safeName}_dsc = {{");
        sb.AppendLine($"    .glyph_bitmap = __{safeName}_bitmap,");
        sb.AppendLine($"    .glyph_dsc = __{safeName}_dsc,");
        sb.AppendLine($"    .cmaps = __{safeName}_cmaps,");
        sb.AppendLine("    .kern_dsc = NULL,");
        sb.AppendLine("    .kern_scale = 0,");
        sb.AppendLine($"    .cmap_num = {ranges.Count},");
        sb.AppendLine($"    .bpp = {asset.Bpp},");
        sb.AppendLine("    .kern_classes = 0,");
        sb.AppendLine("    .bitmap_format = 0,");
        sb.AppendLine("};");
        sb.AppendLine();

        sb.AppendLine("/* public font object */");
        sb.AppendLine($"const lv_font_t {safeName} = {{");
        sb.AppendLine("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,");
        sb.AppendLine("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,");
        sb.AppendLine($"    .line_height = {lineHeight},");
        sb.AppendLine($"    .base_line = {baseLine},");
        sb.AppendLine($"    .dsc = &{safeName}_dsc,");
        sb.AppendLine("    .subpx = LV_FONT_SUBPX_NONE,");
        sb.AppendLine($"    .underline_position = {underlinePos},");
        sb.AppendLine($"    .underline_thickness = {underlineThick},");
        sb.AppendLine("};");
    }

    private static void WriteImageLvgl9(StringBuilder sb, string name, ImageAsset asset, ImageEngine.PixelResult result)
    {
        // 确保变量名是合法 C 标识符（不能以数字开头）
        var safeName = !char.IsLetter(name[0]) && name[0] != '_' ? "img_" + name : name;

        string cfConst = asset.Format switch
        {
            "RGB565" => "LV_COLOR_FORMAT_RGB565",
            "RGB888" => "LV_COLOR_FORMAT_RGB888",
            "ARGB8888" => "LV_COLOR_FORMAT_ARGB8888",
            "I1" => "LV_COLOR_FORMAT_I1",
            _ => "LV_COLOR_FORMAT_RGB888"
        };
        int stride = asset.Format switch
        {
            "RGB565" => result.Width * 2,
            "RGB888" => result.Width * 3,
            "ARGB8888" => result.Width * 4,
            "I1" => (result.Width + 7) / 8,
            _ => result.Width * result.BytesPerPixel
        };

        sb.AppendLine("#include \"lvgl.h\"");
        sb.AppendLine();
        sb.AppendLine("#ifndef LV_ATTRIBUTE_LARGE_CONST");
        sb.AppendLine("#define LV_ATTRIBUTE_LARGE_CONST const");
        sb.AppendLine("#endif");
        sb.AppendLine();

        sb.AppendLine($"static LV_ATTRIBUTE_LARGE_CONST const uint8_t __{safeName}_data[{result.Data.Length}] = {{");
        for (int i = 0; i < result.Data.Length; i++)
        {
            sb.Append($"0x{result.Data[i]:X2}, ");
            if ((i + 1) % 16 == 0) sb.AppendLine();
        }
        sb.AppendLine();
        sb.AppendLine("};");
        sb.AppendLine();

        sb.AppendLine("/* image descriptor */");
        sb.AppendLine($"const lv_image_dsc_t {safeName} = {{");
        sb.AppendLine("    .header = {");
        sb.AppendLine("        .magic = LV_IMAGE_HEADER_MAGIC,");
        sb.AppendLine($"        .cf = {cfConst},");
        sb.AppendLine("        .flags = 0,");
        sb.AppendLine($"        .w = {result.Width},");
        sb.AppendLine($"        .h = {result.Height},");
        sb.AppendLine($"        .stride = {stride},");
        sb.AppendLine("        .reserved_2 = 0");
        sb.AppendLine("    },");
        sb.AppendLine($"    .data_size = sizeof(__{safeName}_data),");
        sb.AppendLine($"    .data = __{safeName}_data,");
        sb.AppendLine("    .reserved = NULL,");
        sb.AppendLine("    .reserved_2 = NULL");
        sb.AppendLine("};");
    }
}
